image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "Example.Test"

before_script:
    - "cd src"
    - "dotnet restore"

build:
    stage: build
    environment:
        name: staging-portal
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "cd $test"
        - "dotnet test"
